#^ENWWW$
#^ENWWW(NEEE|SSE)$
#^ENWWW(NEEE|SSE(EE|N))$
#^ENNWSWW(NEWS|)SSSEEN(WNSE|)EE(SWEN|)NNN$
#^ESSWWN(E|NNENN(EESS(WNSE|)SSS|WWWSSSSE(SW|NNNE)))$
#^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$
#^N(EE|W(W|N)N)N$
